version: '3.9'
name: dvd_rental_dev
services:
  database:
    container_name: dvd-rental.dev.database
    image: postgres:14.4-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
