export const tableNames = {
  customer: 'customer',
  film: 'film',
  filmActor: 'film_actor',
  filmCategory: 'film_category',
  language: 'language',
  category: 'category',
  actor: 'actor',
  address: 'address',
  city: 'city',
  country: 'country',
  store: `store`,
  payment: `payment`,
  rental: `rental`,
  staff: `staff`,
  inventory: 'inventory',
};
